- .github/workflows/ci.yml
- fastexcel-core/pom.xml
fix basic unit-tests workflow runs failure.
> [fix] fix workflow run failure

- .github/workflows/ci.yml
- fastexcel-core/pom.xml
- fastexcel-test/pom.xml
- pom.xml
1. Update the open-source license to MIT.
2. Resolve issues with the basic unit test scripts.
> 
1. 更新项目的开源许可证为MIT
2. 修复基础的单元测试脚本
> fix:modify license and workflow

- fastexcel-core/src/main/java/cn/idev/excel/fileconvertor/BaseExcelConverter.java
- fastexcel-core/src/main/java/cn/idev/excel/fileconvertor/FileConverterContext.java
update:Correction of property name spelling error，fountPath-> fontPath
> update:Correction of property name spelling error

- fastexcel-core/src/main/java/cn/idev/excel/support/ExcelTypeEnum.java
- fastexcel-test/src/test/java/cn/idev/excel/test/core/excludeorinclude/ExcludeOrIncludeDataTest.java
- pom.xml
- style/codestyle/idea/codestyle.xml
- Remove Redundant Validation in File Encryption Process
- refactor code style
- update pom.xml
> refactor: Remove Redundant Validation in File Encryption Process

- fastexcel-core/pom.xml
> build: update poi-ooxml version

- fastexcel-core/pom.xml
- fastexcel-test/pom.xml
- pom.xml
> build: update Lombok dependency

- src/test/java/plus/easyexcel/test/demo/fill/FillTest.java
- src/test/java/plus/easyexcel/test/demo/read/ReadTest.java
- src/test/java/plus/easyexcel/test/demo/web/WebTest.java
- src/test/java/plus/easyexcel/test/demo/write/WriteTest.java
These files seem less useful.
Also, the links inside are broken.
> chore: drop old code

- fastexcel-core/src/main/java/cn/idev/excel/read/processor/DefaultAnalysisEventProcessor.java
- fastexcel-test/src/test/java/cn/idev/excel/test/core/simple/SimpleData.java
- fastexcel-test/src/test/java/cn/idev/excel/test/core/simple/SimpleDataListener.java
- fastexcel-test/src/test/java/cn/idev/excel/test/core/simple/SimpleDataTest.java
- Added JavaDoc and inline comments for simple read/write test
- Added a test case for reading a sheet by `sheetNo`
#212
> doc: add JavaDoc and inline comments for simple test

- fastexcel-test/src/test/java/cn/idev/excel/test/demo/rare/WriteTest.java
- fastexcel-test/src/test/java/cn/idev/excel/test/demo/write/DemoData.java
Add JavaDoc for uncommon test cases
> doc: Add JavaDoc for uncommon test cases

- fastexcel-core/src/main/java/cn/idev/excel/analysis/ExcelAnalyserImpl.java
…ty, implementation details, usage).
> docs :comments regarding the ExcelAnalyserImpl

- CONTRIBUTING.md
Just add code style xml setting as latest suggestion
> docs: add code style setting

- .github/workflows/release.yml
- mvnw
> chore: revert ci action and mvnw

- fastexcel-test/src/test/java/cn/idev/excel/test/temp/WriteV34Test.java
Existing test failed by additional field in sample data.
Just fix the data issue and format as FastExcel format.
Before Change:
After Change:
Root Cause:
> fix: complex header test

- fastexcel-test/src/test/java/cn/idev/excel/test/temp/dataformat/DataFormatTest.java
1. Format as current standards
2. Fix incorrect file
3. Fix NPE issue
4. Disabled invalid case by POI issue on Chinese format
Before:
After:
> fix: fix data format

- pom.xml
In my local environment, it can pass the unit tests.I'm going to try github action
- [PR-335](https://github.com/fast-excel/fastexcel/pull/335) 
- [issue-347](https://github.com/fast-excel/fastexcel/issues/347)
> build: upgrade Apache POI to version 5.4.1

- fastexcel-core/src/main/java/cn/idev/excel/read/listener/ModelBuildEventListener.java
- fastexcel-test/src/test/java/cn/idev/excel/test/demo/read/DemoChainAccessorsData.java
- fastexcel-test/src/test/java/cn/idev/excel/test/demo/read/ReadTest.java
fix https://github.com/alibaba/easyexcel/issues/3524
> fix: fix model binding issue

- fastexcel-core/src/main/java/cn/idev/excel/write/handler/EscapeHexCellWriteHandler.java
- fastexcel-test/src/test/java/cn/idev/excel/test/demo/write/WriteTest.java
> fix: escape hexadecimal-encoded

- .github/pull_request_template.md
- README.md
- README_EN.md
update README file
- add DeepWiki badge
- add ReadmeX badge
> doc: add DeepWiki and ReadmeX badges

- .editorconfig
- pom.xml
> chore: trim whitespaces for other files

- .github/workflows/ci.yml
- pom.xml
#414 
support jdk8 and jdk8+ `mvn install`.
> chore: update pom.xml for improved formatting and add JDK 8+ profile

- docs/zh-CN/community/contribution.md
- docs/zh-CN/community/development.md
- docs/zh-CN/help/core-class.md
- docs/zh-CN/help/parameter.md
Related issue: #443 
- update development guidelines
- update contribution guidelines
- update parameter documentation
- add Converter interface documentation
> docs: update Chapter 5 and Chapter 6

- .github/pull_request_template.md
update pull request template to include contributing guide acknowledgment
.github/pull_request_template.md
> docs: update pull request template to include contributing guide acknowledgment

- .github/workflows/deploy-docs.yml
> fix: update GitHub Actions to use DOC_PAT_TOKEN for deployment

- website/docs/read/converter.md
- website/docs/read/csv.md
- website/docs/read/exception.md
- website/docs/read/extra.md
- website/docs/read/head.md
- website/docs/read/num-rows.md
- website/docs/read/pojo.md
- website/docs/read/sheet.md
- website/docs/read/simple.md
- website/docs/read/spring.md
Related: https://github.com/fast-excel/fastexcel/issues/443
- translate all files in Chapter 2 (Read) from CN to EN
- test locally by command: `yarn start`
> docs: update English Chapter 2-Read

- website/docs/write/csv.md
- website/docs/write/extra.md
- website/docs/write/format.md
- website/docs/write/head.md
- website/docs/write/image.md
- website/docs/write/pojo.md
- website/docs/write/sheet.md
- website/docs/write/simple.md
- website/docs/write/spring.md
- website/docs/write/style.md
Related: https://github.com/fast-excel/fastexcel/issues/443
- translate all files in Chapter 3 (Write) from CN to EN
- test locally by command: `yarn start`
> docs: update English Chapter 3-Write

- website/docs/fill/fill.md
- website/docs/help/annotation.md
- website/docs/help/core-class.md
- website/docs/help/faq.md
- website/docs/help/large-data.md
- website/docs/help/parameter.md
Related: #443 
- update Chapter 4 in English Version
- update Chapter 6 in English Version
> docs: update Chapter 4 and 6 in English Version

- .github/workflows/markdownlint.yml
chore: add markdown lint check for markdown files on push and pull request
Related: #423
.github/workflows/markdownlint.yml
> chore: add markdown lint check for markdown files on push and pull request

- .github/dependabot.yml
- .github/pull_request_template.md
optimize github workflow settings
- update the link to the Contributing Guide in the pull request template
- remove GitHub Actions from dependabot config
> chore: optimize dependabot and PR templates in workflow

- fastexcel-support/pom.xml
- fastexcel/pom.xml
- pom.xml
> release: update version

- .github/workflows/fuzz-tests.yml
Fix runner issue for https://github.com/fast-excel/fastexcel/actions/runs/17513058343/workflow
.github/workflows/fuzz-tests.yml
> chore: update fuzz testing workflow to set JAZZER_ARGS at step level

- fastexcel/src/test/java/cn/idev/excel/csv/CsvData.java
- fastexcel/src/test/java/cn/idev/excel/csv/CsvDataListener.java
- fastexcel/src/test/java/cn/idev/excel/csv/CsvFormatTest.java
migrate CSV unit tests from the example module
> chore: migrate csv unit tests from the example module

- website/docusaurus.config.js
> chore:Update repository and project names in configchre
